In [5]:
import numpy as np

a = np.random.randn(5)

In [6]:
print(a)

[-1.06086677 -0.74371948  0.27212286 -1.04380416 -0.61388353]


In [7]:
print(a.shape)

(5,)


In [8]:
print(a.T)

[-1.06086677 -0.74371948  0.27212286 -1.04380416 -0.61388353]


In [10]:
print(np.dot(a,a.T))

3.21898792734


In [11]:
a = np.random.randn(5,1)
print(a)

[[ 0.72126041]
 [-0.70001225]
 [-1.02866906]
 [-1.47856309]
 [-2.4687028 ]]


In [12]:
print(a.T)

[[ 0.72126041 -0.70001225 -1.02866906 -1.47856309 -2.4687028 ]]


In [13]:
print(np.dot(a,a.T))

[[ 0.52021658 -0.50489112 -0.74193827 -1.06642903 -1.7805776 ]
 [-0.50489112  0.49001715  0.72008094  1.03501227  1.7281222 ]
 [-0.74193827  0.72008094  1.05816003  1.5209521   2.53947819]
 [-1.06642903  1.03501227  1.5209521   2.18614882  3.65013285]
 [-1.7805776   1.7281222   2.53947819  3.65013285  6.09449354]]


In [15]:
#a = np.random.randn(1,5)
#print(a)

In [18]:
assert(a.shape == (1,5))